# Generated by Django 4.1.3 on 2022-12-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discount",
            field=models.IntegerField(default=0),
        ),
    ]
