# Generated by Django 4.1.3 on 2022-12-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_seattoreserve_alter_ticket_seats_delete_seatreserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seats',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seats',
            field=models.ManyToManyField(to='cinema.seattoreserve'),
        ),
    ]
