# Generated by Django 4.1.3 on 2022-12-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_ticket_screening_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reservation_type',
            field=models.CharField(default='adult', max_length=5),
        ),
    ]
