# Generated by Django 4.1.3 on 2022-12-14 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0008_alter_ticket_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='client_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
